In [49]:
import os
import numpy as np
import pandas as pd

In [50]:
train_df = pd.read_csv( '/home/yupaporn/codes/USAI/Traindf.csv')#แก้
conf_mat = pd.crosstab(train_df['Views'],train_df['Sub_class'],rownames=['5-FP Class'],colnames=['15AB Class'])
conf_mat

15AB Class  AB01  AB02  AB03  AB04  AB05  AB06  AB07  AB081  AB082  AB083  \
5-FP Class                                                                  
FP-A          84   109    42    84    34    59     2     22     21      8   
FP-B         130   103    24    37    60     5    51     57     48     23   
FP-C          81    61    19    38     4     0    21     45     40     12   
FP-D           0     0     0    19     0     0     0      0      0      0   
FP-E           0     0     0     0     0     0     0      0      0      0   

15AB Class  AB09  AB10  AB11  AB12  Normal  
5-FP Class                                  
FP-A           0     0     0     0     596  
FP-B           2     0     0     0    1063  
FP-C          96    43    60     0    1015  
FP-D           0     0    34   245     482  
FP-E           0     0     0     0     278

## P(โรค|มุม) = P(มุม|โรค)xP(โรค)

### > หา  P(มุม|โรค)

In [114]:
train_df = pd.read_csv( '/home/yupaporn/codes/USAI/Traindf.csv')#แก้
conf_mat = pd.crosstab(train_df['Views'],train_df['Sub_class'],rownames=['5-FP Class'],colnames=['15AB Class'])
conf_mat

15AB Class  AB01  AB02  AB03  AB04  AB05  AB06  AB07  AB081  AB082  AB083  \
5-FP Class                                                                  
FP-A          84   109    42    84    34    59     2     22     21      8   
FP-B         130   103    24    37    60     5    51     57     48     23   
FP-C          81    61    19    38     4     0    21     45     40     12   
FP-D           0     0     0    19     0     0     0      0      0      0   
FP-E           0     0     0     0     0     0     0      0      0      0   

15AB Class  AB09  AB10  AB11  AB12  Normal  
5-FP Class                                  
FP-A           0     0     0     0     596  
FP-B           2     0     0     0    1063  
FP-C          96    43    60     0    1015  
FP-D           0     0    34   245     482  
FP-E           0     0     0     0     278

In [86]:
view = ['FP-A', 'FP-B', 'FP-C', 'FP-D', 'FP-E']
Class15AB = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083', 'AB09', 'AB10', 'AB11', 'AB12', 'Normal']

In [100]:
p_fp_ = []
fp_ = []
AB_ = []
for i in range(15) :
    fp = [1,1,1,1,1]
    FP = list(conf_mat.iloc[:,i][0:5])
    FP_ = [a +b for a, b in zip(FP, fp)]
    C_all =  sum(FP_)
    view = ['FP-A', 'FP-B', 'FP-C', 'FP-D', 'FP-E']
    for j in range(len(FP_)):
        a = FP_[j]
        p_fp_.append(a)
        AB_.append(Class15AB[i])
        fp_.append(view[j])

In [109]:
# import pandas as pd
# df = pd.DataFrame(AB_, columns =['AB15'])
# df['FP'] = fp_
# df['prob_Subclass_Views'] = p_fp_
# df

In [111]:
prob_Subclass_Views = np.asarray(p_fp_).reshape((15, 5))
bb = prob_Subclass_Views.T
df = pd.DataFrame(bb, columns = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083', 'AB09', 'AB10', 'AB11', 'AB12', 'Normal'])
df

AB01  AB02  AB03  AB04  AB05  AB06  AB07  AB081  AB082  AB083  AB09  AB10  \
0    85   110    43    85    35    60     3     23     22      9     1     1   
1   131   104    25    38    61     6    52     58     49     24     3     1   
2    82    62    20    39     5     1    22     46     41     13    97    44   
3     1     1     1    20     1     1     1      1      1      1     1     1   
4     1     1     1     1     1     1     1      1      1      1     1     1   

   AB11  AB12  Normal  
0     1     1     597  
1     1     1    1064  
2    61     1    1016  
3    35   246     483  
4     1     1     279

In [116]:
conf_mat

15AB Class  AB01  AB02  AB03  AB04  AB05  AB06  AB07  AB081  AB082  AB083  \
5-FP Class                                                                  
FP-A          84   109    42    84    34    59     2     22     21      8   
FP-B         130   103    24    37    60     5    51     57     48     23   
FP-C          81    61    19    38     4     0    21     45     40     12   
FP-D           0     0     0    19     0     0     0      0      0      0   
FP-E           0     0     0     0     0     0     0      0      0      0   

15AB Class  AB09  AB10  AB11  AB12  Normal  
5-FP Class                                  
FP-A           0     0     0     0     596  
FP-B           2     0     0     0    1063  
FP-C          96    43    60     0    1015  
FP-D           0     0    34   245     482  
FP-E           0     0     0     0     278

In [117]:
#หา 
p_fp_ = []
fp_ = []
AB_ = []
for i in range(15) :
    fp = [1,1,1,1,1]
    FP = list(conf_mat.iloc[:,i][0:5])
    FP_ = [a +b for a, b in zip(FP, fp)]
    C_all =  sum(FP_)
    view = ['FP-A', 'FP-B', 'FP-C', 'FP-D', 'FP-E']
    for j in range(len(FP_)):
        a = FP_[j]/C_all
        p_fp_.append(a)
        AB_.append(Class15AB[i])
        fp_.append(view[j])

In [118]:
import pandas as pd
  
# lst = ['FP', 'AB', 'prob_Subclass_Views']
df = pd.DataFrame(AB_, columns =['AB15'])
df['FP'] = fp_
df['prob_Subclass_Views'] = p_fp_
df

AB15    FP  prob_Subclass_Views
0     AB01  FP-A             0.283333
1     AB01  FP-B             0.436667
2     AB01  FP-C             0.273333
3     AB01  FP-D             0.003333
4     AB01  FP-E             0.003333
..     ...   ...                  ...
70  Normal  FP-A             0.173597
71  Normal  FP-B             0.309392
72  Normal  FP-C             0.295435
73  Normal  FP-D             0.140448
74  Normal  FP-E             0.081128

[75 rows x 3 columns]

In [119]:
prob_Subclass_Views = np.asarray(p_fp_).reshape((15, 5))

In [120]:
bb = prob_Subclass_Views.T
bb

array([[0.28333333, 0.39568345, 0.47777778, 0.46448087, 0.33980583,
        0.86956522, 0.03797468, 0.17829457, 0.19298246, 0.1875    ,
        0.00970874, 0.02083333, 0.01010101, 0.004     , 0.17359698],
       [0.43666667, 0.37410072, 0.27777778, 0.20765027, 0.59223301,
        0.08695652, 0.65822785, 0.4496124 , 0.42982456, 0.5       ,
        0.02912621, 0.02083333, 0.01010101, 0.004     , 0.30939227],
       [0.27333333, 0.22302158, 0.22222222, 0.21311475, 0.04854369,
        0.01449275, 0.27848101, 0.35658915, 0.35964912, 0.27083333,
        0.94174757, 0.91666667, 0.61616162, 0.004     , 0.29543472],
       [0.00333333, 0.00359712, 0.01111111, 0.10928962, 0.00970874,
        0.01449275, 0.01265823, 0.00775194, 0.00877193, 0.02083333,
        0.00970874, 0.02083333, 0.35353535, 0.984     , 0.1404478 ],
       [0.00333333, 0.00359712, 0.01111111, 0.00546448, 0.00970874,
        0.01449275, 0.01265823, 0.00775194, 0.00877193, 0.02083333,
        0.00970874, 0.02083333, 0.01010101, 

In [121]:
df = pd.DataFrame(bb, columns = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083', 'AB09', 'AB10', 'AB11', 'AB12', 'Normal'])
df

AB01      AB02      AB03      AB04      AB05      AB06      AB07  \
0  0.283333  0.395683  0.477778  0.464481  0.339806  0.869565  0.037975   
1  0.436667  0.374101  0.277778  0.207650  0.592233  0.086957  0.658228   
2  0.273333  0.223022  0.222222  0.213115  0.048544  0.014493  0.278481   
3  0.003333  0.003597  0.011111  0.109290  0.009709  0.014493  0.012658   
4  0.003333  0.003597  0.011111  0.005464  0.009709  0.014493  0.012658   

      AB081     AB082     AB083      AB09      AB10      AB11   AB12    Normal  
0  0.178295  0.192982  0.187500  0.009709  0.020833  0.010101  0.004  0.173597  
1  0.449612  0.429825  0.500000  0.029126  0.020833  0.010101  0.004  0.309392  
2  0.356589  0.359649  0.270833  0.941748  0.916667  0.616162  0.004  0.295435  
3  0.007752  0.008772  0.020833  0.009709  0.020833  0.353535  0.984  0.140448  
4  0.007752  0.008772  0.020833  0.009709  0.020833  0.010101  0.004  0.081128

In [9]:
# conf_mat_ = pd.crosstab(df['FP'], df['AB15'], rownames=['5-FP Class'], colnames=['15AB Class'])
# conf_mat_

In [10]:
# count_ = train_df[['Sub_class', 'Views', 'Unnamed: 0']].groupby(['Sub_class', 'Views']).count().reset_index()
# count_

In [11]:
# # i = 'AB01'
# prob_Subclass_Views =[]
# for i in Class15AB:
#     df = count_[count_['Sub_class'] == i]
#     C_all =  df['Unnamed: 0'].sum()
#     views = df['Views'].tolist()
# #     print(i)
#     vi = set(view) - set(views)
#     print(vi)

In [12]:
# # i = 'AB01'
# prob_Subclass_Views =[]
# for i in Class15AB:
#     df = count_[count_['Sub_class'] == i]
#     C_all =  df['Unnamed: 0'].sum()
#     views = df['Views'].tolist()
# #     print(i)
# #     vi = set(view) - set(views)
# #     print(vi)
#     for j in views :
#         v = df[df['Views'] == j]['Unnamed: 0'].tolist()[0]/C_all
#         prob_Subclass_Views.append(v)

In [13]:
# len(prob_Subclass_Views)

In [14]:
# probFP_15AB = count_
# probFP_15AB['prob_Subclass_Views'] = prob_Subclass_Views
# probFP_15AB

In [15]:
# #เช็ค
# Normal_all  = 596+1063+1015+482+278
# P_FPA = 596/Normal_all
# P_FPA

In [16]:
# i = 'AB01'
# df = count_[count_['Sub_class'] == i]
# C_all =  df['Unnamed: 0'].sum()
# views = df['Views'].tolist()
# prob_Subclass_Views =[]
# for j in views :
#     v = df[df['Views'] == j]['Unnamed: 0'].tolist()[0]/C_all
#     prob_Subclass_Views.append(v)

### > หา  P(โรค)

In [57]:
count_ = train_df[['Sub_class','Unnamed: 0']].groupby(['Sub_class']).count().reset_index()
count_

Sub_class  Unnamed: 0
0       AB01         295
1       AB02         273
2       AB03          85
3       AB04         178
4       AB05          98
5       AB06          64
6       AB07          74
7      AB081         124
8      AB082         109
9      AB083          43
10      AB09          98
11      AB10          43
12      AB11          94
13      AB12         245
14    Normal        3434

In [58]:
count_['Unnamed: 0'].sum()

5257

In [59]:
C = count_['Unnamed: 0'].tolist()
sum_C = count_['Unnamed: 0'].sum()
prob = []
for i in C:
    prob.append(i/sum_C)
count_['prob_15AB'] = prob

In [60]:
count_

Sub_class  Unnamed: 0  prob_15AB
0       AB01         295   0.056116
1       AB02         273   0.051931
2       AB03          85   0.016169
3       AB04         178   0.033860
4       AB05          98   0.018642
5       AB06          64   0.012174
6       AB07          74   0.014076
7      AB081         124   0.023588
8      AB082         109   0.020734
9      AB083          43   0.008180
10      AB09          98   0.018642
11      AB10          43   0.008180
12      AB11          94   0.017881
13      AB12         245   0.046605
14    Normal        3434   0.653224

### >P(โรค|มุม) 

In [61]:
P_15AB = count_
P_15AB.head()

Sub_class  Unnamed: 0  prob_15AB
0      AB01         295   0.056116
1      AB02         273   0.051931
2      AB03          85   0.016169
3      AB04         178   0.033860
4      AB05          98   0.018642

In [62]:
prob_15AB = P_15AB['prob_15AB'].tolist()
prob_15AB = np.asarray(prob_15AB).reshape((15, 1))
prob_15AB

array([[0.05611566],
       [0.05193076],
       [0.01616892],
       [0.03385962],
       [0.01864181],
       [0.01217424],
       [0.01407647],
       [0.0235876 ],
       [0.02073426],
       [0.00817957],
       [0.01864181],
       [0.00817957],
       [0.01788092],
       [0.04660453],
       [0.65322427]])

In [63]:
prob_Subclass_Views

array([[0.28333333, 0.43666667, 0.27333333, 0.00333333, 0.00333333],
       [0.39568345, 0.37410072, 0.22302158, 0.00359712, 0.00359712],
       [0.47777778, 0.27777778, 0.22222222, 0.01111111, 0.01111111],
       [0.46448087, 0.20765027, 0.21311475, 0.10928962, 0.00546448],
       [0.33980583, 0.59223301, 0.04854369, 0.00970874, 0.00970874],
       [0.86956522, 0.08695652, 0.01449275, 0.01449275, 0.01449275],
       [0.03797468, 0.65822785, 0.27848101, 0.01265823, 0.01265823],
       [0.17829457, 0.4496124 , 0.35658915, 0.00775194, 0.00775194],
       [0.19298246, 0.42982456, 0.35964912, 0.00877193, 0.00877193],
       [0.1875    , 0.5       , 0.27083333, 0.02083333, 0.02083333],
       [0.00970874, 0.02912621, 0.94174757, 0.00970874, 0.00970874],
       [0.02083333, 0.02083333, 0.91666667, 0.02083333, 0.02083333],
       [0.01010101, 0.01010101, 0.61616162, 0.35353535, 0.01010101],
       [0.004     , 0.004     , 0.004     , 0.984     , 0.004     ],
       [0.17359698, 0.30939227, 0.

In [64]:
prob_15AB_FP = prob_15AB * prob_Subclass_Views
prob_15AB_FP

array([[1.58994357e-02, 2.45038362e-02, 1.53382791e-02, 1.87052184e-04,
        1.87052184e-04],
       [2.05481420e-02, 1.94273343e-02, 1.15816801e-02, 1.86801291e-04,
        1.86801291e-04],
       [7.72514954e-03, 4.49136601e-03, 3.59309281e-03, 1.79654640e-04,
        1.79654640e-04],
       [1.57271439e-02, 7.03095846e-03, 7.21598368e-03, 3.70050445e-03,
        1.85025223e-04],
       [6.33459594e-03, 1.10402958e-02, 9.04942278e-04, 1.80988456e-04,
        1.80988456e-04],
       [1.05862990e-02, 1.05862990e-03, 1.76438317e-04, 1.76438317e-04,
        1.76438317e-04],
       [5.34549474e-04, 9.26552421e-03, 3.92002947e-03, 1.78183158e-04,
        1.78183158e-04],
       [4.20554064e-03, 1.06052764e-02, 8.41108128e-03, 1.82849593e-04,
        1.82849593e-04],
       [4.00134824e-03, 8.91209382e-03, 7.45705809e-03, 1.81879466e-04,
        1.81879466e-04],
       [1.53366939e-03, 4.08978505e-03, 2.21530023e-03, 1.70407710e-04,
        1.70407710e-04],
       [1.80988456e-04, 5.4296

In [65]:
b = prob_15AB_FP.T
b

array([[1.58994357e-02, 2.05481420e-02, 7.72514954e-03, 1.57271439e-02,
        6.33459594e-03, 1.05862990e-02, 5.34549474e-04, 4.20554064e-03,
        4.00134824e-03, 1.53366939e-03, 1.80988456e-04, 1.70407710e-04,
        1.80615360e-04, 1.86418109e-04, 1.13397758e-01],
       [2.45038362e-02, 1.94273343e-02, 4.49136601e-03, 7.03095846e-03,
        1.10402958e-02, 1.05862990e-03, 9.26552421e-03, 1.06052764e-02,
        8.91209382e-03, 4.08978505e-03, 5.42965367e-04, 1.70407710e-04,
        1.80615360e-04, 1.86418109e-04, 2.02102537e-01],
       [1.53382791e-02, 1.15816801e-02, 3.59309281e-03, 7.21598368e-03,
        9.04942278e-04, 1.76438317e-04, 3.92002947e-03, 8.41108128e-03,
        7.45705809e-03, 2.21530023e-03, 1.75558802e-02, 7.49793926e-03,
        1.10175370e-02, 1.86418109e-04, 1.92985130e-01],
       [1.87052184e-04, 1.86801291e-04, 1.79654640e-04, 3.70050445e-03,
        1.80988456e-04, 1.76438317e-04, 1.78183158e-04, 1.82849593e-04,
        1.81879466e-04, 1.70407710e-0

In [75]:
conf_mat = pd.crosstab(train_df['Views'],train_df['Sub_class'],rownames=['5-FP Class'],colnames=['15AB Class']).reset_index()
conf_mat

15AB Class 5-FP Class  AB01  AB02  AB03  AB04  AB05  AB06  AB07  AB081  AB082  \
0                FP-A    84   109    42    84    34    59     2     22     21   
1                FP-B   130   103    24    37    60     5    51     57     48   
2                FP-C    81    61    19    38     4     0    21     45     40   
3                FP-D     0     0     0    19     0     0     0      0      0   
4                FP-E     0     0     0     0     0     0     0      0      0   

15AB Class  AB083  AB09  AB10  AB11  AB12  Normal  
0               8     0     0     0     0     596  
1              23     2     0     0     0    1063  
2              12    96    43    60     0    1015  
3               0     0     0    34   245     482  
4               0     0     0     0     0     278

In [67]:
df = pd.DataFrame(b, columns = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083', 'AB09', 'AB10', 'AB11', 'AB12', 'Normal'])
df

AB01      AB02      AB03      AB04      AB05      AB06      AB07  \
0  0.015899  0.020548  0.007725  0.015727  0.006335  0.010586  0.000535   
1  0.024504  0.019427  0.004491  0.007031  0.011040  0.001059  0.009266   
2  0.015338  0.011582  0.003593  0.007216  0.000905  0.000176  0.003920   
3  0.000187  0.000187  0.000180  0.003701  0.000181  0.000176  0.000178   
4  0.000187  0.000187  0.000180  0.000185  0.000181  0.000176  0.000178   

      AB081     AB082     AB083      AB09      AB10      AB11      AB12  \
0  0.004206  0.004001  0.001534  0.000181  0.000170  0.000181  0.000186   
1  0.010605  0.008912  0.004090  0.000543  0.000170  0.000181  0.000186   
2  0.008411  0.007457  0.002215  0.017556  0.007498  0.011018  0.000186   
3  0.000183  0.000182  0.000170  0.000181  0.000170  0.006322  0.045859   
4  0.000183  0.000182  0.000170  0.000181  0.000170  0.000181  0.000186   

     Normal  
0  0.113398  
1  0.202103  
2  0.192985  
3  0.091744  
4  0.052995

In [68]:
FP_ = []
for j in range(5) :
    FP = list(df.iloc[j,:][0:14])
    fp = []
    if j == 4:
        fp = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1]
        FP_.append(fp)
    else:
        for i in FP:
            fp.append(i)
        fp.append(1)
        FP_.append(fp)

In [69]:
from scipy.special import softmax

In [70]:
# FP_ = []
# for j in range(5) :
#     FP = list(df.iloc[j,:][0:14])
#     fp = []
#     if j == 4:
#         fp = [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,0.01,0.01]
#         FP_.append(fp)
#     else:
#         for i in FP:
#             fp.append(i)
#         fp.append(0.1)
#         FP_.append(fp)

In [71]:
FP = np.array(FP_)
FP.shape

(5, 15)

In [72]:
FP

array([[1.58994357e-02, 2.05481420e-02, 7.72514954e-03, 1.57271439e-02,
        6.33459594e-03, 1.05862990e-02, 5.34549474e-04, 4.20554064e-03,
        4.00134824e-03, 1.53366939e-03, 1.80988456e-04, 1.70407710e-04,
        1.80615360e-04, 1.86418109e-04, 1.00000000e+00],
       [2.45038362e-02, 1.94273343e-02, 4.49136601e-03, 7.03095846e-03,
        1.10402958e-02, 1.05862990e-03, 9.26552421e-03, 1.06052764e-02,
        8.91209382e-03, 4.08978505e-03, 5.42965367e-04, 1.70407710e-04,
        1.80615360e-04, 1.86418109e-04, 1.00000000e+00],
       [1.53382791e-02, 1.15816801e-02, 3.59309281e-03, 7.21598368e-03,
        9.04942278e-04, 1.76438317e-04, 3.92002947e-03, 8.41108128e-03,
        7.45705809e-03, 2.21530023e-03, 1.75558802e-02, 7.49793926e-03,
        1.10175370e-02, 1.86418109e-04, 1.00000000e+00],
       [1.87052184e-04, 1.86801291e-04, 1.79654640e-04, 3.70050445e-03,
        1.80988456e-04, 1.76438317e-04, 1.78183158e-04, 1.82849593e-04,
        1.81879466e-04, 1.70407710e-0

In [73]:
dfs_ = pd.DataFrame(FP, columns = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083', 'AB09', 'AB10', 'AB11', 'AB12', 'Normal'])
dfs_

AB01      AB02      AB03      AB04      AB05      AB06      AB07  \
0  0.015899  0.020548  0.007725  0.015727  0.006335  0.010586  0.000535   
1  0.024504  0.019427  0.004491  0.007031  0.011040  0.001059  0.009266   
2  0.015338  0.011582  0.003593  0.007216  0.000905  0.000176  0.003920   
3  0.000187  0.000187  0.000180  0.003701  0.000181  0.000176  0.000178   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

      AB081     AB082     AB083      AB09      AB10      AB11      AB12  \
0  0.004206  0.004001  0.001534  0.000181  0.000170  0.000181  0.000186   
1  0.010605  0.008912  0.004090  0.000543  0.000170  0.000181  0.000186   
2  0.008411  0.007457  0.002215  0.017556  0.007498  0.011018  0.000186   
3  0.000183  0.000182  0.000170  0.000181  0.000170  0.006322  0.045859   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

   Normal  
0     1.0  
1     1.0  
2     1.0  
3     1.0  
4     1.0

In [314]:
# FP_ = []
# for j in range(5) :
#     FP = list(df_.iloc[j,:][0:14])
#     fp = []
#     if j == 4:
#         fp = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1]
#         FP_.append(fp)
#     else:
#         a = softmax(FP)
#         for i in a:
#             fp.append(i)
#         fp.append(1)
#         FP_.append(fp)

In [301]:
# FP_=[]
# for j in range(5) :
#     FP = list(df_.iloc[j,:][0:15])
    
#     fp = []
#     a = softmax(FP)
#     for i in a:
#         fp.append(i)
#     FP_.append(fp)

In [74]:
dfs_

AB01      AB02      AB03      AB04      AB05      AB06      AB07  \
0  0.015899  0.020548  0.007725  0.015727  0.006335  0.010586  0.000535   
1  0.024504  0.019427  0.004491  0.007031  0.011040  0.001059  0.009266   
2  0.015338  0.011582  0.003593  0.007216  0.000905  0.000176  0.003920   
3  0.000187  0.000187  0.000180  0.003701  0.000181  0.000176  0.000178   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

      AB081     AB082     AB083      AB09      AB10      AB11      AB12  \
0  0.004206  0.004001  0.001534  0.000181  0.000170  0.000181  0.000186   
1  0.010605  0.008912  0.004090  0.000543  0.000170  0.000181  0.000186   
2  0.008411  0.007457  0.002215  0.017556  0.007498  0.011018  0.000186   
3  0.000183  0.000182  0.000170  0.000181  0.000170  0.006322  0.045859   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

   Normal  
0     1.0  
1     1.0  
2     1.0  
3     1.0  
4     1.0

In [35]:
FP_ = []
for j in range(5) :
    FP = list(dfs_.iloc[j,:][0:14])
    fp = []
    fp_max = sum(FP)
    if j == 4:
        fp = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1]
        FP_.append(fp)
    else:
        for i in FP:
            fp.append(i/fp_max)
        fp.append(1)
        FP_.append(fp)

In [36]:
# FP_=[]
# for j in range(5) :
#     FP = list(dfs_.iloc[j,:][0:15])
#     fp_max = max(FP)
#     fp = []
#     for i in FP:
#         fp.append(i/fp_max)
#     FP_.append(fp)

In [37]:
FP = np.array(FP_)
FP.shape

(5, 15)

In [38]:
df_ = pd.DataFrame(FP, columns = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083', 'AB09', 'AB10', 'AB11', 'AB12', 'Normal'])
# df_.iloc[3,:].sum()
df_

AB01      AB02      AB03      AB04      AB05      AB06      AB07  \
0  0.181057  0.233995  0.087971  0.179095  0.072136  0.120553  0.006087   
1  0.241404  0.191392  0.044248  0.069267  0.108765  0.010429  0.091281   
2  0.158010  0.119311  0.037015  0.074337  0.009322  0.001818  0.040383   
3  0.003233  0.003229  0.003105  0.063960  0.003128  0.003050  0.003080   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

      AB081     AB082     AB083      AB09      AB10      AB11      AB12  \
0  0.047891  0.045566  0.017465  0.002061  0.001941  0.002057  0.002123   
1  0.104480  0.087799  0.040291  0.005349  0.001679  0.001779  0.001837   
2  0.086648  0.076820  0.022821  0.180855  0.077241  0.113499  0.001920   
3  0.003160  0.003144  0.002945  0.003128  0.002945  0.109262  0.792630   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

   Normal  
0     1.0  
1     1.0  
2     1.0  
3     1.0  
4     1.0

In [39]:
df_.iloc[0,:]

AB01      0.181057
AB02      0.233995
AB03      0.087971
AB04      0.179095
AB05      0.072136
AB06      0.120553
AB07      0.006087
AB081     0.047891
AB082     0.045566
AB083     0.017465
AB09      0.002061
AB10      0.001941
AB11      0.002057
AB12      0.002123
Normal    1.000000
Name: 0, dtype: float64

In [40]:
df_.iloc[0,:].sum()

2.0

In [42]:
FP

array([[0.18105747, 0.23399539, 0.08797143, 0.17909547, 0.07213627,
        0.12055324, 0.00608727, 0.04789129, 0.04556602, 0.01746492,
        0.00206104, 0.00194055, 0.00205679, 0.00212287, 1.        ],
       [0.24140401, 0.19139192, 0.04424751, 0.06926677, 0.10876549,
        0.01042929, 0.091281  , 0.10447981, 0.08779912, 0.04029126,
        0.00534912, 0.0016788 , 0.00177937, 0.00183653, 1.        ],
       [0.15800986, 0.11931062, 0.03701485, 0.07433667, 0.00932241,
        0.00181761, 0.04038284, 0.08664817, 0.07682014, 0.02282129,
        0.18085485, 0.07724128, 0.11349901, 0.00192042, 1.        ],
       [0.00323303, 0.0032287 , 0.00310517, 0.06395999, 0.00312823,
        0.00304958, 0.00307974, 0.0031604 , 0.00314363, 0.00294535,
        0.00312823, 0.00294535, 0.10926227, 0.79263033, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 

In [367]:
FP = np.array(FP_)
FP.shape

(5, 15)

In [368]:
df_ = pd.DataFrame(FP, columns = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05', 'AB06', 'AB07', 'AB081', 'AB082', 'AB083', 'AB09', 'AB10', 'AB11', 'AB12', 'Normal'])
df_

AB01      AB02      AB03      AB04      AB05      AB06      AB07  \
0  0.773765  1.000000  0.375954  0.765380  0.308281  0.515195  0.026014   
1  1.000000  0.792828  0.183292  0.286933  0.450554  0.043203  0.378125   
2  0.873683  0.659704  0.204666  0.411029  0.051546  0.010050  0.223289   
3  0.004079  0.004073  0.003918  0.080693  0.003947  0.003847  0.003885   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

      AB081     AB082     AB083      AB09      AB10      AB11      AB12  \
0  0.204668  0.194730  0.074638  0.008808  0.008293  0.008790  0.009072   
1  0.432801  0.363702  0.166904  0.022158  0.006954  0.007371  0.007608   
2  0.479103  0.424761  0.126186  1.000000  0.427090  0.627570  0.010619   
3  0.003987  0.003966  0.003716  0.003947  0.003716  0.137848  1.000000   
4  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

   Normal  
0     1.0  
1     1.0  
2     1.0  
3     1.0  
4     1.0

In [221]:
# p_15AB_FP = []
# for i in Class15AB:
#     a = P_FP_15AB[P_FP_15AB['Sub_class']==i]['prob_Subclass_Views'].tolist()
#     b = P_15AB[P_15AB['Sub_class']==i]['prob_15AB'].tolist()
# #     c = np.prod(a)*b[0]
#     p_15AB_FP.append(np.prod(a)*b[0])
#     print(i)
# #     print(np.prod(a))

In [227]:
#เช็ค normal
# print(sum([0.17355853232382062, 0.3095515433896331, 0.2955736750145603, 0.1403610949330227, 0.0809551543389633]))
# 0.17355853232382062* 0.3095515433896331* 0.2955736750145603* 0.1403610949330227* 0.0809551543389633*0.6532242723987065

In [224]:
# Class15AB

In [225]:
# P_15AB_FP = P_15AB[['Sub_class']]
# P_15AB_FP['prob_15AB_5FP'] = p_15AB_FP
# P_15AB_FP

In [226]:
# P_15AB_FP['prob_15AB_5FP'].tolist()