In [1]:
import pandas as pd
df = pd.read_csv( '/home/yupaporn/CCA_Project/result_BiTNet.csv')#แก้

In [2]:
df

Unnamed: 0     Case Abs Position Sub Position     Class  \
0              0  AB01_40           P1           P1  Abnormal   
1              1  AB01_40           P2           P2  Abnormal   
2              2  AB01_40           P4          P41  Abnormal   
3              3  AB01_40           P5          P51  Abnormal   
4              4  AB01_40           P3          P31  Abnormal   
...          ...      ...          ...          ...       ...   
1307        1307      350           P3          P32    Normal   
1308        1308      350           P4          P42    Normal   
1309        1309      350           P5          P52    Normal   
1310        1310      350           P6          P61    Normal   
1311        1311      350           P8           P8    Normal   

                                              Path Full  \
0     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...   
1     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...   
2     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...   
3     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...   
4     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...   
...                                                 ...   
1307  /media/tohn/HDD/VISION_dataset/USAI/US images ...   
1308  /media/tohn/HDD/VISION_dataset/USAI/US images ...   
1309  /media/tohn/HDD/VISION_dataset/USAI/US images ...   
1310  /media/tohn/HDD/VISION_dataset/USAI/US images ...   
1311  /media/tohn/HDD/VISION_dataset/USAI/US images ...   

                                              Path Crop Views  fold  \
0     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...  FP-A     2   
1     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...  FP-A     2   
2     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...  FP-B     2   
3     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...  FP-C     2   
4     /media/tohn/HDD/VISION_dataset/USAI/ABnormal01...  FP-B     2   
...                                                 ...   ...   ...   
1307  /media/tohn/HDD/VISION_dataset/USAI/US images ...  FP-B     2   
1308  /media/tohn/HDD/VISION_dataset/USAI/US images ...  FP-B     2   
1309  /media/tohn/HDD/VISION_dataset/USAI/US images ...  FP-C     2   
1310  /media/tohn/HDD/VISION_dataset/USAI/US images ...  FP-C     2   
1311  /media/tohn/HDD/VISION_dataset/USAI/US images ...  FP-E     2   

                15AB  ...      Rtop    Rwidth   Rheight  Sub_class_New  \
0     MildFattyLiver  ...  0.148873  0.513514  0.346614           AB01   
1     MildFattyLiver  ...  0.154849  0.560377  0.428287           AB01   
2     MildFattyLiver  ...  0.150865  0.667984  0.711155           AB01   
3     MildFattyLiver  ...  0.107041  0.690385  0.653386           AB01   
4     MildFattyLiver  ...  0.146881  0.672515  0.625498           AB01   
...              ...  ...       ...       ...       ...            ...   
1307          Normal  ...       NaN       NaN       NaN         Normal   
1308          Normal  ...       NaN       NaN       NaN         Normal   
1309          Normal  ...       NaN       NaN       NaN         Normal   
1310          Normal  ...       NaN       NaN       NaN         Normal   
1311          Normal  ...       NaN       NaN       NaN         Normal   

      tag_AjNit  tag_AjWan  Test150  Spilt  15AB_None Prob_None  
0           NaN        NaN    False   Test     Normal  0.413035  
1           NaN        NaN    False   Test       AB01  0.110668  
2           NaN        NaN    False   Test       AB02  0.091490  
3           NaN        NaN    False   Test       AB01  0.075286  
4           NaN        NaN    False   Test       AB02  0.065060  
...         ...        ...      ...    ...        ...       ...  
1307        NaN        NaN    False   Test     Normal  1.000000  
1308       Easy       Easy    False   Test     Normal  0.515819  
1309       Easy       Easy     True   Test     Normal  0.995000  
1310       Hard       Easy     True   Test     Normal  0.906968  
1311        NaN        NaN    False   Test     N

In [3]:
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

In [16]:
col_name = ['Case', 'Act_label', 'Pred_label','Num_PredCase']
dff2 = pd.DataFrame(columns = col_name)

In [17]:
case = list(set(df['Case']))
pred_label = []
num_case = []
act_label = []

for i in case:
    cas_pred = set(df[df['Case'] == i]['15AB_None'])
    cas_act = set(df[df['Case'] == i]['Sub_class_New'])
    pred_label.append(list(cas_pred))
    act_label.append(list(cas_act))
    num_case.append(len(cas_pred))

dff2['Pred_label'] = pred_label
dff2['Case'] = case
dff2['Num_PredCase'] = num_case
dff2['Act_label'] = act_label  

In [18]:
dff2

Case Act_label    Pred_label  Num_PredCase
0     AB083_9   [AB083]       [AB083]             1
1    AB12_280    [AB12]        [AB12]             1
2      AB07_1    [AB07]      [Normal]             1
3     AB02_58    [AB02]        [AB02]             1
4     Ab1_135    [AB01]      [Normal]             1
..        ...       ...           ...           ...
373   AB11_67    [AB11]        [AB11]             1
374    AB01_2    [AB01]  [AB01, AB02]             2
375       143  [Normal]      [Normal]             1
376   AB06_32    [AB06]        [AB06]             1
377    AB12_4    [AB12]        [AB12]             1

[378 rows x 4 columns]

## Preparation data

In [19]:
dff2

Case Act_label    Pred_label  Num_PredCase
0     AB083_9   [AB083]       [AB083]             1
1    AB12_280    [AB12]        [AB12]             1
2      AB07_1    [AB07]      [Normal]             1
3     AB02_58    [AB02]        [AB02]             1
4     Ab1_135    [AB01]      [Normal]             1
..        ...       ...           ...           ...
373   AB11_67    [AB11]        [AB11]             1
374    AB01_2    [AB01]  [AB01, AB02]             2
375       143  [Normal]      [Normal]             1
376   AB06_32    [AB06]        [AB06]             1
377    AB12_4    [AB12]        [AB12]             1

[378 rows x 4 columns]

### 1. แปลงข้อมูล

In [34]:
import numpy as np

In [56]:
# ab = [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
# [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
# [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
# [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
# [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
# [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
# [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
# [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
# [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
# [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
# [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
# [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
# [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
# [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
# [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]
# ab=np.array(ab)
# ab.shape

In [57]:
# # Actual class
# cla_act = []
# for i in Act:
#     a = str(list(i)[0])
#     for j in range(15):
#         if a == class_[j]:
#             cla_act.append(list(ab[j]))

In [58]:
Act = dff2['Act_label'].tolist()
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

cla_act = []
for i in Act:
    a = str(list(i)[0])
    for j in range(len(class_)):
        if a == class_[j]:
            m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
            m[j] = 1
            cla_act.append(m)

In [59]:
cla_act

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [60]:
Act

[['AB083'],
 ['AB12'],
 ['AB07'],
 ['AB02'],
 ['AB01'],
 ['AB05'],
 ['AB082'],
 ['AB07'],
 ['AB081'],
 ['AB11'],
 ['AB11'],
 ['AB06'],
 ['AB11'],
 ['AB10'],
 ['Normal'],
 ['AB12'],
 ['Normal'],
 ['Normal'],
 ['AB05'],
 ['AB083'],
 ['AB12'],
 ['AB06'],
 ['AB04'],
 ['Normal'],
 ['AB081'],
 ['AB02'],
 ['AB06'],
 ['AB083'],
 ['AB11'],
 ['AB11'],
 ['Normal'],
 ['AB06'],
 ['AB12'],
 ['AB03'],
 ['AB05'],
 ['AB06'],
 ['AB082'],
 ['AB10'],
 ['AB11'],
 ['AB081'],
 ['Normal'],
 ['Normal'],
 ['AB082'],
 ['Normal'],
 ['AB06'],
 ['AB09'],
 ['AB03'],
 ['AB11'],
 ['Normal'],
 ['Normal'],
 ['AB12'],
 ['AB04'],
 ['AB12'],
 ['AB04'],
 ['AB07'],
 ['AB07'],
 ['AB081'],
 ['Normal'],
 ['AB11'],
 ['AB11'],
 ['AB081'],
 ['AB11'],
 ['Normal'],
 ['AB081'],
 ['AB11'],
 ['AB01'],
 ['AB09'],
 ['AB01'],
 ['AB11'],
 ['AB05'],
 ['AB10'],
 ['AB083'],
 ['AB11'],
 ['AB03'],
 ['AB05'],
 ['AB11'],
 ['AB081'],
 ['AB02'],
 ['AB07'],
 ['AB12'],
 ['AB01'],
 ['AB04'],
 ['Normal'],
 ['AB081'],
 ['AB082'],
 ['AB081'],
 ['AB03'],


In [74]:
Pred = dff2['Pred_label'].tolist()
class_ = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

cla_pred = []
for i in Pred:
    if len(list(i)) == 1:
        a = str(list(i)[0])
        for j in range(len(class_)):
            if a == class_[j]:
                m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                m[j] = 1
                cla_pred.append(m)
    else:
        m = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        for j in list(i):
            print(list(i))
            for k in range(len(class_)):
                if j == class_[k]:
                    m[k] = 1
        cla_pred.append(m)
        print(m)

['Normal', 'AB05']
['Normal', 'AB05']
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
['Normal', 'AB05']
['Normal', 'AB05']
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
['AB06', 'AB05']
['AB06', 'AB05']
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB03', 'AB02']
['AB03', 'AB02']
[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB03', 'AB02']
['AB03', 'AB02']
[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB04', 'Normal', 'AB06', 'AB07']
['AB04', 'Normal', 'AB06', 'AB07']
['AB04', 'Normal', 'AB06', 'AB07']
['AB04', 'Normal', 'AB06', 'AB07']
[0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
['AB01', 'Normal', 'AB02']
['AB01', 'Normal', 'AB02']
['AB01', 'Normal', 'AB02']
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
['AB03', 'AB02']
['AB03', 'AB02']
[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['AB01', 'Normal', 'AB02']
['AB01', 'Normal', 'AB02']
['AB01', 'Normal', 'AB02']
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
['AB082', 'AB081']
['AB082', 'AB081']
[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 

In [75]:
cla_pred

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [76]:
Pred

[['AB083'],
 ['AB12'],
 ['Normal'],
 ['AB02'],
 ['Normal'],
 ['Normal', 'AB05'],
 ['AB082'],
 ['Normal'],
 ['AB081'],
 ['AB12'],
 ['AB12'],
 ['AB07'],
 ['Normal'],
 ['AB10'],
 ['Normal'],
 ['AB04'],
 ['Normal'],
 ['Normal'],
 ['Normal', 'AB05'],
 ['Normal'],
 ['AB12'],
 ['AB06', 'AB05'],
 ['AB04'],
 ['Normal'],
 ['AB12'],
 ['AB03', 'AB02'],
 ['Normal'],
 ['Normal'],
 ['AB11'],
 ['AB12'],
 ['Normal'],
 ['Normal'],
 ['AB12'],
 ['AB03'],
 ['AB05'],
 ['AB06'],
 ['Normal'],
 ['Normal'],
 ['Normal'],
 ['Normal'],
 ['Normal'],
 ['Normal'],
 ['AB081'],
 ['Normal'],
 ['AB06'],
 ['AB09'],
 ['AB03', 'AB02'],
 ['AB12'],
 ['Normal'],
 ['Normal'],
 ['AB12'],
 ['AB04', 'Normal', 'AB06', 'AB07'],
 ['AB12'],
 ['AB04'],
 ['AB07'],
 ['AB07'],
 ['Normal'],
 ['Normal'],
 ['AB12'],
 ['AB11'],
 ['AB12'],
 ['AB12'],
 ['Normal'],
 ['Normal'],
 ['AB11'],
 ['AB01'],
 ['AB09'],
 ['AB01', 'Normal', 'AB02'],
 ['AB11'],
 ['AB05'],
 ['AB10'],
 ['AB082'],
 ['AB12'],
 ['AB03', 'AB02'],
 ['AB05'],
 ['AB12'],
 ['Normal']

## Evaluation

In [79]:
import numpy as np
y_true = np.array(cla_act)
y_pred = np.array(cla_pred)

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.5952380952380952

In [81]:
print("Actual \n", y_true)
print("\nPredicted \n",y_pred)

Actual 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]

Predicted 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [82]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_true, y_pred)

array([[[345,   9],
        [  5,  19]],

       [[340,  15],
        [  4,  19]],

       [[361,   9],
        [  3,   5]],

       [[357,   6],
        [  2,  13]],

       [[358,   4],
        [  3,  13]],

       [[362,   2],
        [  5,   9]],

       [[360,   4],
        [  5,   9]],

       [[341,   5],
        [ 14,  18]],

       [[347,   4],
        [ 12,  15]],

       [[366,   1],
        [  7,   4]],

       [[352,   0],
        [  6,  20]],

       [[367,   1],
        [  6,   4]],

       [[321,   2],
        [ 35,  20]],

       [[313,  33],
        [  8,  24]],

       [[235,  72],
        [  0,  71]]])

In [84]:
from sklearn.metrics import classification_report

label_names = ['AB01', 'AB02','AB03','AB04','AB05','AB06','AB07','AB081','AB082','AB083','AB09','AB10','AB11','AB12','Normal']

print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

        AB01       0.68      0.79      0.73        24
        AB02       0.56      0.83      0.67        23
        AB03       0.36      0.62      0.45         8
        AB04       0.68      0.87      0.76        15
        AB05       0.76      0.81      0.79        16
        AB06       0.82      0.64      0.72        14
        AB07       0.69      0.64      0.67        14
       AB081       0.78      0.56      0.65        32
       AB082       0.79      0.56      0.65        27
       AB083       0.80      0.36      0.50        11
        AB09       1.00      0.77      0.87        26
        AB10       0.80      0.40      0.53        10
        AB11       0.91      0.36      0.52        55
        AB12       0.42      0.75      0.54        32
      Normal       0.50      1.00      0.66        71

   micro avg       0.61      0.70      0.65       378
   macro avg       0.70      0.66      0.65       378
weighted avg       0.70   